pipeline:
  name: undeploy-virtualan
  identifier: undeployvirtualan
  tags: {}
  projectIdentifier: ias_template
  orgIdentifier: default
  stages:
    - stage:
        name: undeploy
        identifier: undeploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: <+input>
            serviceInputs: <+input>
          environment:
            environmentRef: <+input>
            deployToAll: false
            environmentInputs: <+input>
            serviceOverrideInputs: <+input>
            infrastructureDefinitions: <+input>
          execution:
            steps:
              - step:
                  type: K8sDelete
                  name: K8sDelete_1
                  identifier: K8sDelete_1
                  spec:
                    deleteResources:
                      type: ManifestPath
                      spec:
                        manifestPaths:
                          - " servicedeploy.yaml"
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
