pipeline:
  name: undeploy-virtualan
  identifier: undeployvirtualan
  tags: {}
  template:
    templateRef: org.undeploypipeline
    versionLabel: v1
    gitBranch: elan-harness-demo
  projectIdentifier: ias_template
  orgIdentifier: default
